:bug: Add annotation inspection support
konveyor/java-analyzer-bundle pull request #104
Opened 2024-07-16 12:37 UTC by jmle

- Adds support for annotation queries, allowing to inspect matched FIELDs, METHOD_DECLARATIONs and TYPE declarations.
- Corrects a bug with parenthesis handling.
- Adds support for METHOD_DECLARATION.

2024-07-16 13:06 UTC, shawn-hurley commented on java-analyzer-bundle.core/src/main/java/io/konveyor/tackle/core/internal/SampleDelegateCommandHandler.java
> +    /**
Thank you so much!

2024-07-16 13:14 UTC, pranavgaikwad requested changes

2024-07-16 14:41 UTC, shawn-hurley approved these changes
LGTM

2024-07-16 15:09 UTC, merged

2024-07-24 14:20 UTC, jmle commented
Also fixes https://github.com/konveyor/java-analyzer-bundle/issues/36